# Chapter 3 : Modeling in the Time Domain
---

In [1]:
import sys

if (path := "C:/Users/Tom/pycharm-projects/python-control") not in sys.path:
    sys.path.append(path)

import numpy as np

from python_control import TransferFunction, StateSpace

## 3.5 : Converting a Transfer Function to State Space

### Example 3.4 : Converting a Transfer Function with a Constant Term in the Numerator

Find the state space representation in phase-variable form for the transfer function:
$$\frac{{C\left( s \right)}}{{R\left( s \right)}} = \frac{{24}}{{{s^3} + 9{s^2} + 26s + 24}}$$

In [2]:
G = TransferFunction.from_coefficients(num=[24], den=[1, 9, 26, 24])
G.expr

24.0/(1.0*s**3 + 9.0*s**2 + 26.0*s + 24.0)

Convert transfer function to state space:

In [3]:
ss = StateSpace.from_transfer_function(G)
ss = ss.transform('controller')

> **Note**<br>
A state space representation can take multiple forms. `StateSpace.from_transfer_function()` returns the default state space representation form it gets from the function `control.tf2ss` (see [Python Control Systems Library](https://python-control.readthedocs.io/)). To transform a state space representation from one form into another, the function `transform` of the `StateSpace` object can be called, specifying the desired form. The possible forms are mentioned in the docstring of this function. However, the phase-variable form is not supported. Here, the state space representation is transformed into the *controller canonical form*, which looks likes the *phase-variable form*; only the ordering of the state variables is reversed.

**System matrix** ${\bf{A}}$

In [4]:
ss.A

array([[ -9., -26., -24.],
       [  1.,   0.,   0.],
       [  0.,   1.,   0.]])

**Input matrix** ${\bf{B}}$

In [5]:
ss.B

array([[1.],
       [0.],
       [0.]])

**Output Matrix** ${\bf{C}}$

In [6]:
ss.C

array([[ 0.,  0., 24.]])

**Feedforward matrix** ${\bf{D}}$

In [7]:
ss.D

array([[0.]])

### Example 3.5 : Converting a Transfer Function with a Polynomial in the Numerator

Find the state-space representation of the transfer function:
$$\frac{{C\left( s \right)}}{{R\left( s \right)}} = \frac{{{s^2} + 7s + 2}}{{{s^3} + 9{s^2} + 26s + 24}}$$

In [8]:
G = TransferFunction.from_coefficients(num=[1, 7, 2], den=[1, 9, 26, 24])
G.expr

(1.0*s**2 + 7.0*s + 2.0)/(1.0*s**3 + 9.0*s**2 + 26.0*s + 24.0)

Convert transfer function to state space:

In [9]:
ss = StateSpace.from_transfer_function(G)
ss = ss.transform('controller')

**System matrix** ${\bf{A}}$

In [10]:
ss.A

array([[ -9., -26., -24.],
       [  1.,   0.,   0.],
       [  0.,   1.,   0.]])

**Input matrix** ${\bf{B}}$

In [11]:
ss.B

array([[1.],
       [0.],
       [0.]])

**Output Matrix** ${\bf{C}}$

In [12]:
ss.C

array([[1., 7., 2.]])

**Feedforward matrix** ${\bf{D}}$

In [13]:
ss.D

array([[0.]])

## 3.6 : Converting from State Space to a Transfer Function

### Example 3.6 : State-Space Representation to Transfer Function

Find the transfer function $T(s) = Y(s) / U(s)$, given the system defined by:
$$
{\bf{\dot x}} = \left[ {\begin{array}{*{20}{c}}
0&1&0\\
0&0&1\\
{ - 1}&{ - 2}&{ - 3}
\end{array}} \right] \cdot {\bf{x}} + \left[ {\begin{array}{*{20}{c}}
{10}\\
0\\
0
\end{array}} \right] \cdot u
$$

$$
y = \left[ {\begin{array}{*{20}{c}}
1&0&0
\end{array}} \right] \cdot {\bf{x}}
$$

**System matrix** ${\bf{A}}$

In [14]:
A = np.array([
    [0, 1, 0],
    [0, 0, 1],
    [-1, -2, -3]
])

**Input matrix** ${\bf{B}}$

In [15]:
B = np.array([
    [10],
    [0],
    [0]
])

**Output Matrix** ${\bf{C}}$

In [16]:
C = np.array([[1, 0, 0]])

Create `StateSpace` object:

In [17]:
ss = StateSpace(A, B, C)

Convert state space to transfer function:

In [18]:
G = TransferFunction.from_state_space(ss)
G.expr

(10.0*s**2 + 30.0*s + 20.0)/(1.0*s**3 + 3.0*s**2 + 2.0*s + 1.0)